name: Optimized BPB Build (Stage 2)
 
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 1 * * *"
 
permissions:
  contents: write 
 
jobs:
  prepare:
    runs-on: ubuntu-latest 
    outputs:
      node-cache: ${{{{ steps.node-cache.outputs.cache-hit  }}}}
    steps:
      - uses: actions/checkout@v4 
      
      - name: Node.js 环境预加载 [5]()
        uses: actions/setup-node@v4 
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json" 
 
      - name: 二进制工具预缓存 [2]()
        uses: actions/cache@v4 
        id: binary-cache 
        with:
          path: |
            ~/.npm 
            /usr/local/bin/javascript-obfuscator 
          key: ${{{{ runner.os  }}}}-bin-${{{{ hashFiles('**/package-lock.json')  }}}}
 
  build:
    needs: prepare 
    runs-on: ubuntu-latest 
    env:
      NODE_OPTIONS: "--max-old-space-size=4096 --optimize-for-size"
    steps:
      - uses: actions/checkout@v4 
        with:
          ref: ${{{{ github.ref  }}}}
 
      - name: 并行资源加载 [6]()
        run: |
          (wget -qO origin.js  https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/refs/heads/main/build/unobfuscated-worker.js)  &
          (npm install -g pnpm && pnpm install -g javascript-obfuscator) &
          wait 
 
      - name: 增量混淆处理 [7]()
        run: |
          if [ origin.js  -nt _worker.js  ]; then 
            javascript-obfuscator origin.js  --output _worker.js  \
            --compact true \
            --control-flow-flattening-threshold 0.5 \
            --dead-code-injection-threshold 0.3 \
            --identifier-names-generator hexadecimal \
            --string-array-encoding 'rc4' \
            --parallel true 
          else 
            echo "No changes detected, skipping obfuscation"
          fi 
 
      - name: 智能提交 [3]()
        uses: stefanzweifel/git-auto-commit-action@v5 
        with:
          branch: main 
          commit_message: ':zap: Optimized build'
          commit_author: 'github-actions[bot]'
          push_options: '--force'
