name: Ultra-Optimized BPB Build 
 
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 1 * * *"
 
permissions:
  contents: write 
 
jobs:
  prepare:
    runs-on: ubuntu-latest 
    outputs:
      cache-key: ${{ steps.cache-npm.outputs.cache-key  }}
    steps:
      - uses: actions/checkout@v4 
      
      - name: Preload Node.js  with JIT 
        uses: actions/setup-node@v4 
        with:
          node-version: "20.x"
          cache: "npm"
          flags: "--max-old-space-size=2048"
 
      - name: Cache global packages [1]()
        id: cache-npm 
        uses: actions/cache@v4 
        with:
          path: |
            ~/.npm 
            /usr/local/lib/node_modules 
          key: ${{ runner.os  }}-npm-${{ hashFiles('**/package-lock.json')  }}
 
  build:
    needs: prepare 
    runs-on: ubuntu-latest 
    timeout-minutes: 5 
    steps:
      - name: Parallel tasks 
        uses: robinraju/release-downloader@v1.7 
        with:
          repository: "bia-pain-bache/BPB-Worker-Panel"
          fileName: "unobfuscated-worker.js" 
          out-file-path: "origin.js" 
 
      - name: Smart Obfuscation ()
        run: |
          javascript-obfuscator origin.js  --output _worker.js  \
          --compact true \
          --control-flow-flattening true \
          --dead-code-injection-threshold 0.5 \
          --identifier-names-generator hexadecimal \
          --string-array-encoding 'rc4' \
          --transform-object-keys true \
          options:
            cpuQuota: 0.8  # 限制CPU使用率 
 
      - name: Conditional Commit ()
        uses: stefanzweifel/git-auto-commit-action@v5 
        with:
          branch: main 
          commit_message: ':zap: Optimized build'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>' 
          push_options: '--force'
          skip_dirty_check: true 
        env:
          GIT_COMMITTER_NAME: github-actions 
          GIT_COMMITTER_EMAIL: actions@github.com  
 
  post-build:
    needs: build 
    runs-on: ubuntu-latest 
    steps:
      - name: Cleanup artifacts ()
        run: |
          rm -rf origin.js  
          npm cache clean --force 
