name: Optimized Build Obfuscate BPB Panel 
 
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 1 * * *"
 
permissions:
  contents: write 
 
jobs:
  prepare:
    runs-on: ubuntu-latest 
    outputs:
      cache-key: ${{ steps.cache-npm.outputs.cache-key  }}
    steps:
      - uses: actions/checkout@v4 
      
      - name: Cache npm global packages 
        id: cache-npm 
        uses: actions/cache@v4 
        with:
          path: ~/.npm 
          key: ${{ runner.os  }}-npm-global-${{ hashFiles('**/package-lock.json')  }}
          restore-keys: |
            ${{ runner.os  }}-npm-global-
 
  build:
    needs: prepare 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4 
 
      - name: Set up Node.js  (Optimized)
        uses: actions/setup-node@v4 
        with:
          node-version: "latest"
          flags: "--max-old-space-size=4096"
 
      - name: Install dependencies 
        run: |
          npm config set registry https://registry.npmmirror.com/ 
          npm install -g javascript-obfuscator 
 
      - name: Clone BPB workjs (Optimized)
        run: |
          if [ ! -f origin.js  ]; then 
            wget -q -O origin.js  https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/refs/heads/main/build/unobfuscated-worker.js  
          fi 
 
      - name: Obfuscate BPB worker js (Optimized)
        run: |
          javascript-obfuscator origin.js  --output _worker.js  \
          --compact true \
          --control-flow-flattening true \
          --control-flow-flattening-threshold 0.7 \
          --dead-code-injection true \
          --dead-code-injection-threshold 0.5 \
          --identifier-names-generator hexadecimal \
          --rename-globals true \
          --string-array true \
          --string-array-encoding 'rc4' \
          --string-array-threshold 0.6 \
          --transform-object-keys true \
          --unicode-escape-sequence true \
          --simplify true 
 
      - uses: stefanzweifel/git-auto-commit-action@v5 
        with:
          branch: main 
          commit_message: ':zap: Optimized build'
